---
- name: Install MySQL Server and backup packages
  apt:
    state: latest
    pkg:
      - mysql-server
      - python-mysqldb
      - automysqlbackup

- name: Change MySQL charset to prevent MySQL error 1709
  template:
    src: templates/60-charset.cnf
    dest: /etc/mysql/mysql.conf.d/60-charset.cnf
  when: ansible_distribution_major_version|int > 15
  notify: restart mysql

- name: Start Mysql Service
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Check hostname
  command: hostname -f
  register: realhostname

- name: Allow arch to access automysqlbackup directory
  file:
    path: /var/lib/automysqlbackup
    state: directory
    group: manager
