---
- name: Install packages needed to compile TFS
  apt:
    state: latest
    pkg:
      - git
      - cmake
      - build-essential
      - libmysqlclient-dev
      - libboost-system-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libcrypto++-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libpugixml-dev

- name: Install systemd service for TFS
  template:
    src: templates/{{item}}
    dest: /etc/systemd/system/{{item}}
  with_items:
    - tfs.service
